
package com.uindata.czs.cxf.wsdl.clinet;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-02-28T17:41:10.400+08:00
 * Generated source version: 3.2.6
 *
 */
public final class MySqlGreeterPortType_MySqlGreeterPort_Client {

    private static final QName SERVICE_NAME = new QName("http://DefaultNamespace", "MySqlGreeter");

    private MySqlGreeterPortType_MySqlGreeterPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MySqlGreeter.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MySqlGreeter ss = new MySqlGreeter(wsdlURL, SERVICE_NAME);
        MySqlGreeterPortType port = ss.getMySqlGreeterPort();

        {
        System.out.println("Invoking operation...");
        java.lang.String _operation_arg0 = "";
        java.lang.String _operation__return = port.operation(_operation_arg0);
        System.out.println("operation.result=" + _operation__return);


        }

        System.exit(0);
    }

}
