
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.uindata.czs.cxf.wsdl.clinet;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-02-28T17:41:10.415+08:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "MySqlGreeter",
                      portName = "MySqlGreeterPort",
                      targetNamespace = "http://DefaultNamespace",
                      wsdlLocation = "http://localhost:9001/MySql?wsdl",
                      endpointInterface = "com.uindata.czs.cxf.wsdl.clinet.MySqlGreeterPortType")

public class MySqlGreeterPortImpl implements MySqlGreeterPortType {

    private static final Logger LOG = Logger.getLogger(MySqlGreeterPortImpl.class.getName());

    /* (non-Javadoc)
     * @see MySqlGreeterPortType#operation(java.lang.String arg0)*
     */
    public java.lang.String operation(java.lang.String arg0) {
        LOG.info("Executing operation operation");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
