package com.uindata.czs.cxf.wsdl.clinet;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-02-28T17:41:10.436+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "MySqlGreeter",
                  wsdlLocation = "http://localhost:9001/MySql?wsdl",
                  targetNamespace = "http://DefaultNamespace")
public class MySqlGreeter extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://DefaultNamespace", "MySqlGreeter");
    public final static QName MySqlGreeterPort = new QName("http://DefaultNamespace", "MySqlGreeterPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9001/MySql?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MySqlGreeter.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9001/MySql?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MySqlGreeter(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MySqlGreeter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MySqlGreeter() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MySqlGreeter(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MySqlGreeter(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MySqlGreeter(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MySqlGreeterPortType
     */
    @WebEndpoint(name = "MySqlGreeterPort")
    public MySqlGreeterPortType getMySqlGreeterPort() {
        return super.getPort(MySqlGreeterPort, MySqlGreeterPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MySqlGreeterPortType
     */
    @WebEndpoint(name = "MySqlGreeterPort")
    public MySqlGreeterPortType getMySqlGreeterPort(WebServiceFeature... features) {
        return super.getPort(MySqlGreeterPort, MySqlGreeterPortType.class, features);
    }

}
