<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="MySqlGreeter" targetNamespace="http://DefaultNamespace"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://DefaultNamespace" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
        <xsd:schema xmlns:tns="http://DefaultNamespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    attributeFormDefault="unqualified" elementFormDefault="qualified"
                    targetNamespace="http://DefaultNamespace">
            <xsd:element name="operation" type="tns:operation"/>
            <xsd:complexType name="operation">
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="arg0" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="operationResponse" type="tns:operationResponse"/>
            <xsd:complexType name="operationResponse">
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="return" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="operationResponse">
        <wsdl:part name="parameters" element="tns:operationResponse">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="operation">
        <wsdl:part name="parameters" element="tns:operation">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="MySqlGreeterPortType">
        <wsdl:operation name="operation">
            <wsdl:input name="operation" message="tns:operation">
            </wsdl:input>
            <wsdl:output name="operationResponse" message="tns:operationResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MySqlGreeterSoapBinding" type="tns:MySqlGreeterPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="operation">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="operation">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="operationResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MySqlGreeter">
        <wsdl:port name="MySqlGreeterPort" binding="tns:MySqlGreeterSoapBinding">
            <soap:address location="http://localhost:9090/MySqlGreeterPort"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
