
package com.uindata.czs.cxf.clinet;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-02-28T17:41:10.431+08:00
 * Generated source version: 3.2.6
 *
 */

public class MySqlGreeterPortType_MySqlGreeterPort_Server{

    protected MySqlGreeterPortType_MySqlGreeterPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MySqlGreeterPortImpl();
        String address = "http://localhost:9001/MySql";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new MySqlGreeterPortType_MySqlGreeterPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
