package com.uindata.czs.cxf.clinet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-02-28T17:41:10.424+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://DefaultNamespace", name = "MySqlGreeterPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MySqlGreeterPortType {

    @WebMethod
    @RequestWrapper(localName = "operation", targetNamespace = "http://DefaultNamespace", className = "com.uindata.czs.cxf.clinet.Operation")
    @ResponseWrapper(localName = "operationResponse", targetNamespace = "http://DefaultNamespace", className = "com.uindata.czs.cxf.clinet.OperationResponse")
    @WebResult(name = "return", targetNamespace = "http://DefaultNamespace")
    public java.lang.String operation(
        @WebParam(name = "arg0", targetNamespace = "http://DefaultNamespace")
        java.lang.String arg0
    );
}
